<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Data Entry Field</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>631aeecf-9d60-4683-87fd-6e4582eb1bc2</testSuiteGuid>
   <testCaseLink>
      <guid>2b495681-f760-4ed8-b529-2499485fbb26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c967b6db-283a-4b89-be74-f839bb18811c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Entry Field/Create New Data Entry - Expect SUCCESS - Saw text success create form</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d0d17eb-815c-488e-931c-ff297bb2757a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aff8452-f9c7-406f-a8a1-30afddf1cfff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ee042f7-f13f-4e2a-bd66-4a51726943b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbc87a0-ee9a-450b-922f-6cdd80892654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6b81d4-5e75-417f-9dab-c6da6e888a8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d74b27ec-35c6-41af-836f-3a0daafc52b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>872b784c-74d2-46d2-bf15-0d07393da65f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6e74f54-93ae-4c37-b3be-6c6ca679efba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3d838c6-7c7a-4d5c-a29c-824f7ed93d20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8072bd52-daa8-439a-ad63-b4537bcdd958</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Data Entry Field/Edit Data Entry - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d0d17eb-815c-488e-931c-ff297bb2757a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aff8452-f9c7-406f-a8a1-30afddf1cfff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ee042f7-f13f-4e2a-bd66-4a51726943b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbc87a0-ee9a-450b-922f-6cdd80892654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6b81d4-5e75-417f-9dab-c6da6e888a8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d74b27ec-35c6-41af-836f-3a0daafc52b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>872b784c-74d2-46d2-bf15-0d07393da65f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>665cb64a-349a-44ef-ba61-205c6d8ec21f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9ab6b99-bbc4-4ec1-ad8e-b86ae1ac4598</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Data Entry Field/View Data Entry - Expect SUCCESS</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
