<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Site</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5a018450-e500-469c-bc9b-362a549cae50</testSuiteGuid>
   <testCaseLink>
      <guid>b6634a51-b5c0-40a6-9730-52b1a926b48c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6ea38e8-bded-45f1-a516-b3e171c84c1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site/Create New Site - Expect SUCCESS - Saw dialog success and text success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91591034-972f-4f6d-976b-fd7814a73ccf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1cc5e74-b498-4253-b762-f6c7682e1283</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6ae0275-4450-459e-9102-35a8eb8757c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Create New Site - Expect FAILED - Duplicate site name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6522bc9-cae1-48b3-9e07-a19855b50a5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>326b8049-0b53-467a-a29a-41b67228633f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55beaa8e-3185-43d4-ad0b-5eb0d8269d83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Create New Site Failed - Empty Fields Status</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8f87fbb-eaff-442b-8cc8-d56f78538075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e299bf62-01af-4d04-a2a5-11245dd31fef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db79a301-4fc1-4669-b316-daf9846fdeba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67c3f2fb-2f14-4673-8512-8875709e667a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a70951be-6fea-4296-90cf-31704d5e6c5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Edit Site Failed - Already Exist</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce8ec2c-19ed-45d7-9228-d4b20124ab7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f25f946-4eae-4b17-baf4-9e2a5aa7d3a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edf3b200-afe4-41cd-b410-408ba29bf9c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Edit Site Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26ebbac3-404c-4234-b13e-7d4fd8dee9ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f386fe44-0107-471b-a550-1182f80b8207</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Filter Site - Found Site</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>767996d9-8812-49be-b4e6-017e3519b8c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>697b4589-e28c-403c-8661-62f9c8fac871</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Filter Site - Found Status</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89bffe1f-e772-4195-a69b-393b58b91217</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da0391a3-eeee-4adc-862a-9ffa984f870c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Delete Site</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cd160d27-206c-4ee3-9225-e56b8a701957</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tearDown/Kill Chrome</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>873c31c4-531c-4f0b-a931-0f0d9c3c6d12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site/Create New Site Failed - Empty Fields Site Name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f48fcfdc-45f1-4964-9da8-b4eb41f09f7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52bbd0b3-3561-4ffa-a43e-8a867cdb29b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a018301-b60f-4f50-bc7c-ec2e91c3f815</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5179d79f-4bfb-4d67-b0e2-180f54f0c753</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b58451c-9337-452d-8a5e-2745d5fd74a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Site/Create New Site Failed - Empty Fields</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>701798cc-0ee0-4973-b268-c672201a3c4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e39cce2e-e6e1-465a-9ad9-930d3f211710</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6f3d2ac-c2f9-44db-816a-9405a78005b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd0af145-81f8-4ea5-bc71-b7173425c24b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
