<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Project Attribute</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>08020a93-605a-48ed-ad52-f8859cb85df9</testSuiteGuid>
   <testCaseLink>
      <guid>55f29be4-63ec-44a7-b99e-3de85fedc661</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>272a2fee-6a1d-4b03-9a1b-ae8a0028a94f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project Attribute/Create New Project Attribute - Expect SUCCESS - Saw text success create project attribute</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c7e9fda2-458d-426b-b57d-3b0649d05663</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/250 project attribute</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c7e9fda2-458d-426b-b57d-3b0649d05663</testDataLinkId>
         <type>DATA_COLUMN_INDEX</type>
         <value></value>
         <variableId>2938bbbf-7265-4035-9afa-3f2e81894c4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7e9fda2-458d-426b-b57d-3b0649d05663</testDataLinkId>
         <type>DATA_COLUMN_INDEX</type>
         <value></value>
         <variableId>72034238-5fed-456b-b476-88a8caea7984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7e9fda2-458d-426b-b57d-3b0649d05663</testDataLinkId>
         <type>DATA_COLUMN_INDEX</type>
         <value></value>
         <variableId>eab0241d-6e88-42a5-8482-a40905390c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7e9fda2-458d-426b-b57d-3b0649d05663</testDataLinkId>
         <type>DATA_COLUMN_INDEX</type>
         <value></value>
         <variableId>9e85ab0f-54b0-4c46-aab7-70cbb645e573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7e9fda2-458d-426b-b57d-3b0649d05663</testDataLinkId>
         <type>DATA_COLUMN_INDEX</type>
         <value></value>
         <variableId>6275413f-3c27-45cb-bf61-7c23c4de5419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142934e6-f34c-4b1d-8c9f-09685a1c4e5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a4c70c-fea4-4411-b2e2-b9f2f1cf6ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a79f7116-4182-48ea-8a7e-aef29e9edc9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ed40a0c-bdff-4247-9bcf-852ca9f59fa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project Attribute/Edit Project Attribute - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99a30c7-fd52-4b9b-b88c-c0b74933f97f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2938bbbf-7265-4035-9afa-3f2e81894c4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72034238-5fed-456b-b476-88a8caea7984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab0241d-6e88-42a5-8482-a40905390c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e85ab0f-54b0-4c46-aab7-70cbb645e573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6275413f-3c27-45cb-bf61-7c23c4de5419</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82eb176f-a097-4745-9fbd-addc06a9a642</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project Attribute/Search Project Attribute - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>64ad7b80-aa42-4249-a0fb-7cef1409e771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project Attribute/Delete Project Attribute - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99a30c7-fd52-4b9b-b88c-c0b74933f97f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2938bbbf-7265-4035-9afa-3f2e81894c4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72034238-5fed-456b-b476-88a8caea7984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab0241d-6e88-42a5-8482-a40905390c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e85ab0f-54b0-4c46-aab7-70cbb645e573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6275413f-3c27-45cb-bf61-7c23c4de5419</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
