<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Project</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>26a6ca99-8b02-4a1c-a7d6-34012d0fe849</testSuiteGuid>
   <testCaseLink>
      <guid>b5f0418c-3571-45ae-aef3-618ee1e24a4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd758fcf-cf0f-462e-98fc-cb339a437a70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Create New Project - Expect SUCCESS - Saw dialog success and text success create project</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7132eb8b-cbb6-475c-9bf2-d450a7232df4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cda7987-aab1-41ef-917d-4a52972d85e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69540aba-77a5-417e-8ace-816858b3f54c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91d71d8-4430-4a55-b3f1-bfa2d44db048</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dc3884c-d716-4706-85e1-8bc902aac7b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c7b3f8b-a952-48fb-9e3d-15924e6f89b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1005b5c-ea11-44b3-aa22-9bff7bff5fcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>709151b7-56c3-45f3-a7ef-2d407f87cda3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>927b9997-824e-438c-ac78-2c8b161f3958</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Create New Project - Expect FAILED - Project Name Duplicate</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bd2ee1b7-641e-4468-bfcd-bec76661aab1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Delete Project - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0039495e-6c91-4e26-aaaf-a34cdd33b9dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ada4d356-e425-43ce-a8c5-417c6a5e4872</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c66d4c-5cc1-4a64-8ca7-f63cbfec83c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc091978-8368-4542-a075-23bbf6cd3c0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b322ae-0712-4ace-b77e-b62590c8acdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32093c9f-8025-4286-9b2c-e5fb1c8ef117</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Filter Project Manager - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19ec6af3-47f4-4d19-8dcd-ebf81c6ca337</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b252786-d30a-448c-8a4e-90fb8aae36c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c19e60f-3f7c-4199-9a87-59ca63337d88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc31e759-55c9-4c31-ab28-7cedcf44feb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Filter Project Status - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9e8af49-7e73-426f-9dee-5c4a698eefdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7ba4578-9523-44ce-95a4-11108bb3c0d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e58c8ca4-70e6-4f8f-bca0-f503800821f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Search Project Name - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7098519c-77a8-4ac7-ad03-7ec9ac140aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0697a2a-e9c3-46a9-b55c-42dbee43c9f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>040605a1-e96f-47d9-bcf8-6c14be343bf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Refresh Table Project - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c56fdfc-fdb7-43b8-9368-ed5b510d1191</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae69dc1a-468f-4de2-988f-98e66e9fb0b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0ee2379-53bd-4a61-92b0-0ecbc1b9947c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Pagination Table - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66f1d9cb-d5df-44db-9ab0-7fbe60a4573a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2abff1b2-c465-4747-b8f7-cda158953ddc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2d1505b-9695-4bff-9d2f-ee0f8d9f7f86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Expand Project Filter - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>759051e9-766f-45d2-9e05-12733a71ee83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a26d19e-d6c1-48f0-bf25-c7ca1f45932e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8ab2854-31bd-4e64-8961-ac559b390734</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50cccfd0-77ad-4236-a0c5-9a76f4e909bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project/Validation Empty Field - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e01a0d8-5d1e-4179-a225-c205282bee87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca1c3b56-2089-4ea5-8d99-054beaa193bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6737fb56-c92d-47a9-a037-8701f0d318a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0bc3d6f-0a09-492e-ae84-ebffb2eacf6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4857d5ba-2263-48fd-a903-16c3706e6b02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545ddc89-e0c7-4744-a3d9-ee75066ec24b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ce80dd3-3abf-4c83-af32-735a5119b680</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tearDown/Kill Chrome</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
