<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Site User</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>00aa5ce3-75d8-4a22-be78-aa1ff626949b</testSuiteGuid>
   <testCaseLink>
      <guid>2abf8b43-6d8d-4c68-8215-a9cec2ab2533</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9db045e1-b32f-40b2-8b9a-b1a650bbb6e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site User/Create New Site User - Expected Success - Saw dialog success create</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4ef8a54-2424-4fbe-9e9f-77019292969a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ed8e75c-c3f3-465b-8177-715ec71e52c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>223d7396-320e-4f97-913b-66fd98940dc2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b673eef3-e32c-4553-829b-5d372e4c02cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site User/Create New Site User - Expected Failed - Already Exists</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dcd36b6-92d0-424d-b4a1-5cc074f847a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fec230b1-ca42-4b5e-98f2-a8ed759d724f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7881c5-9164-41d6-a8f4-714974aa5d29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bab8fca6-bab2-43df-9ed2-2a50a50f7235</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5eb7c966-874f-4d1e-89a9-e5b7d8c36905</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site User/Edit Site User - Expected Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0e0d64c-f091-4c7d-85a5-f96468726958</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3380d63-471a-45a6-ab95-63cea61caec7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site User/Filter Site User - Expected Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e821d366-4b67-42cd-820f-30435c7fc639</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7d83d3b-198e-4406-928d-e6e036fa2bad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9e26126-a39f-4b23-bb1e-ba91d8497793</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site User/Filter Site User - Expected Failed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc1eae6b-214c-4f8c-95d6-eefbb1d22206</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8cbe851-e15f-439d-81b7-ecbd52fb59cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f341d905-7e40-4530-9179-867bbdecd6d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Site User/Delete Site User</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
