<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Workflow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2ee529c3-05c7-49fe-95c6-ad879b54df63</testSuiteGuid>
   <testCaseLink>
      <guid>2fceff6a-fb2a-496b-80b7-807586601ac1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>926c7c31-1041-4d09-815a-c5b09238e4de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Edit Workflow - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>531e327d-b638-4c8c-aef1-b5512b22ef21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5e8319e-ca23-4650-9607-a103271f4557</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42b3649c-a3e8-43eb-88cf-45f7f7a3fca2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef7c3aee-5d79-4c10-9a62-87df6991a654</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a98414e-d6e5-4b25-a681-31e69b053cb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a01508a-031f-4f48-82cc-357eadaaada0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>148e02ca-8409-4e83-809a-1a13ff5cc6de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78d44a7a-3f3a-4099-8623-6dfb1fdb8a9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Validation Form Workflow - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>11ced278-8907-4059-b8d1-8edcc7d4bf02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/View Worklfow - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>894f0b6c-dc25-4999-90c5-8bb65b153592</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Deploy Workflow - Expect SUCCESS - Saw dialog success and text deployed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee6996ec-d74e-40e3-a081-6a03534d4dd1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e55f3328-3a97-493a-9cfc-27d613933bc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Expand Filter Workflow - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3bcfbb5f-5530-46b5-9a7d-aacaf697c77e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Filter Workflow - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>002d5473-b10f-4f27-a89a-38465e552ff2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Search Workflow - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5cde3325-2358-483f-956f-faada30e71ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Workflow/Refresh Table - Expect SUCCESS</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>123a02b5-87ae-41ef-91a8-2860a6b04763</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tearDown/Kill Chrome</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
