<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Project Attribute</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>022a321a-ab58-4c23-b9c7-f5d40be6e006</testSuiteGuid>
   <testCaseLink>
      <guid>27512a3a-4ba5-4d15-ba70-cc354af155d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Sucess</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01c5a6e-dbc3-44ea-ad35-e617193d516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1332d1d9-bba0-4b30-acd7-8ffa6c812bfb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>345cbe10-2687-4468-bfdd-ab0b9a0248e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Project Attribute/Create New Project Attribute - Expect SUCCESS - Saw text success create project attribute</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2938bbbf-7265-4035-9afa-3f2e81894c4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72034238-5fed-456b-b476-88a8caea7984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab0241d-6e88-42a5-8482-a40905390c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e85ab0f-54b0-4c46-aab7-70cbb645e573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6275413f-3c27-45cb-bf61-7c23c4de5419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>142934e6-f34c-4b1d-8c9f-09685a1c4e5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a4c70c-fea4-4411-b2e2-b9f2f1cf6ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a79f7116-4182-48ea-8a7e-aef29e9edc9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>590ed5c4-5ec7-448d-a664-fa56800d2cc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Project Attribute/Edit Project Attribute - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99a30c7-fd52-4b9b-b88c-c0b74933f97f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2938bbbf-7265-4035-9afa-3f2e81894c4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72034238-5fed-456b-b476-88a8caea7984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab0241d-6e88-42a5-8482-a40905390c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e85ab0f-54b0-4c46-aab7-70cbb645e573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6275413f-3c27-45cb-bf61-7c23c4de5419</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc910834-15ae-4443-9e2b-15176845ab4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Project Attribute/Delete Project Attribute - Expect SUCCESS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99a30c7-fd52-4b9b-b88c-c0b74933f97f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2938bbbf-7265-4035-9afa-3f2e81894c4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72034238-5fed-456b-b476-88a8caea7984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab0241d-6e88-42a5-8482-a40905390c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e85ab0f-54b0-4c46-aab7-70cbb645e573</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6275413f-3c27-45cb-bf61-7c23c4de5419</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
