<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Last Update2021-06-10 011438_fa fa-fw fa-trash-o</name>
   <tag></tag>
   <elementGuidId>67b4e979-f1c9-4b1f-8296-89c5946322ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div[3]/div[3]/div[2]/div[2]/div/div/table/tbody/tr/td[6]/div/span[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-fw.fa-trash-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-trash-o</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container body&quot;]/div[@class=&quot;main_container&quot;]/div[@class=&quot;right_col&quot;]/div[@class=&quot;x_panel&quot;]/div[@class=&quot;x_content&quot;]/div[2]/div[@class=&quot;_loading_overlay_wrapper css-79elbk&quot;]/div[@class=&quot;react-bootstrap-table table-responsive&quot;]/table[@class=&quot;table text-nowrap&quot;]/tbody[1]/tr[1]/td[6]/div[1]/span[@class=&quot;d-inline-block&quot;]/button[@class=&quot;btn-default  undefined btn btn-secondary btn-sm&quot;]/i[@class=&quot;fa fa-fw fa-trash-o&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div[3]/div[3]/div[2]/div[2]/div/div/table/tbody/tr/td[6]/div/span[2]/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button/i</value>
   </webElementXpaths>
</WebElementEntity>
